export const ADD_WORKER="ADD_WORKER";
export const DELETE_WORKER="DELETE_WORKER";

export const ADD_WORKER_SCHEDULE="ADD_WORKER_SCHEDULE";
export const DELETE_WORKER_SCHEDULE="DELETE_WORKER_SCHEDULE";